model:
  weights: models/model.int8.onnx
  use_itn: true
  language: auto
  tokens: models/tokens.txt
  num_threads: 4
web:
  resample_rate: 16000
  max_processing_time: 10
  host: 0.0.0.0
  port: 3000
